### ISSUE TITLE
Fixed ValueIn.object(CharSequence.class)

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#114]
at net.openhft.chronicle.core.util.ObjectUtils.lambda$static$3(ObjectUtils.java:77)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:53)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at net.openhft.chronicle.core.util.ObjectUtils.newInstance(ObjectUtils.java:348)
	at net.openhft.chronicle.wire.SerializationStrategies.newInstance(SerializationStrategies.java:390)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:432)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:503)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.object(BinaryWire.java:2088)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:575)
	at net.openhft.chronicle.engine.server.internal.GenericWireAdapter.lambda$new$4(GenericWireAdapter.java:55)
	at net.openhft.chronicle.engine.server.internal.MapWireHandler$1.lambda$accept$0(MapWireHandler.java:82)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3231)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3215)
	at net.openhft.chronicle.engine.server.internal.MapWireHandler$1.accept(MapWireHandler.java:79)
	at net.openhft.chronicle.engine.server.internal.MapWireHandler$1.accept(MapWireHandler.java:68)
	at net.openhft.chronicle.engine.server.internal.MapWireHandler.process(MapWireHandler.java:344)
	at net.openhft.chronicle.engine.server.internal.EngineWireHandler.onRead0(EngineWireHandler.java:391)
	at net.openhft.chronicle.engine.server.internal.EngineWireHandler.onRead(EngineWireHandler.java:326)
	at net.openhft.chronicle.network.WireTcpHandler.onRead0(WireTcpHandler.java:204)
	at net.openhft.chronicle.network.WireTcpHandler.process(WireTcpHandler.java:157)
	at net.openhft.chronicle.network.TcpEventHandler.invokeHandler(TcpEventHandler.java:325)
	at net.openhft.chronicle.network.TcpEventHandler.action0(TcpEventHandler.java:230)
	at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:186)
	at net.openhft.chronicle.threads.VanillaEventLoop.runAllMediumHandler(VanillaEventLoop.java:352)
	at net.openhft.chronicle.threads.VanillaEventLoop.runMediumLoopOnly(VanillaEventLoop.java:285)
	at net.openhft.chronicle.threads.VanillaEventLoop.runLoop(VanillaEventLoop.java:255)
	at net.openhft.chronicle.threads.VanillaEventLoop.run(VanillaEventLoop.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by peter-lawrey** [comment]
The behaviour changes to treat unknown types as Marshallable, however in this case, it should be a Scalar. I have corrected this by only treating concrete classes as Marshallable by default.

**Comment by RobAustin** [comment]
thanks

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.11), [BOM-2.17.126](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.126)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.11), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.11), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.11), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
