### ISSUE TITLE
Method reader fails to process chained calls if interim method accepts zero / two or more arguments

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#206]
Object instance on which method is invoked is not changed during processing call that accepts zero / two or more arguments. The next call processing fails with a following error:
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.openhft.chronicle.wire.VanillaMethodReader.invoke(VanillaMethodReader.java:454)
	at net.openhft.chronicle.wire.VanillaMethodReader.lambda$addParseletForMethod$7(VanillaMethodReader.java:292)
	at net.openhft.chronicle.wire.VanillaWireParser.parseOne(VanillaWireParser.java:83)
	at net.openhft.chronicle.wire.WireParser.accept(WireParser.java:61)
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne0(VanillaMethodReader.java:502)
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne(VanillaMethodReader.java:476)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
