### ISSUE TITLE
Release resource in test

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#213]
`mvn clean install`

```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 s - in net.openhft.chronicle.wire.Base128LongConverterTest
[Finalizer] WARN net.openhft.chronicle.core.io.TracingReferenceCounted - Discarded without being released
net.openhft.chronicle.core.StackTrace: NativeBytesStore@ri - [] main init INIT on main
	at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:172)
	at net.openhft.chronicle.core.io.TracingReferenceCounted.<init>(TracingReferenceCounted.java:30)
	at net.openhft.chronicle.core.io.ReferenceCountedTracer.onReleased(ReferenceCountedTracer.java:10)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<init>(AbstractReferenceCounted.java:31)
	at net.openhft.chronicle.bytes.AbstractBytesStore.<init>(AbstractBytesStore.java:35)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:86)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:81)
	at net.openhft.chronicle.bytes.NativeBytesStore.of(NativeBytesStore.java:131)
	at net.openhft.chronicle.bytes.NativeBytesStore.nativeStoreWithFixedCapacity(NativeBytesStore.java:137)
	at net.openhft.chronicle.bytes.NativeBytes.nativeBytes(NativeBytes.java:94)
	at net.openhft.chronicle.bytes.Bytes.allocateElasticDirect(Bytes.java:454)
	at net.openhft.chronicle.bytes.HexDumpBytes.<init>(HexDumpBytes.java:47)
	at net.openhft.chronicle.wire.DocumentContextTest.multiMessageBinary(DocumentContextTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.102](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.102), [BOM-2.20.141](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.141)
