### ISSUE TITLE
java.lang.UnsupportedOperationException calling toString

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#214]
```
import net.openhft.chronicle.bytes.BytesIn;
import net.openhft.chronicle.bytes.BytesMarshallable;
import net.openhft.chronicle.bytes.BytesOut;
import net.openhft.chronicle.core.io.IORuntimeException;
import net.openhft.chronicle.wire.SelfDescribingMarshallable;
import org.junit.Test;

public class InnerBytesMarshallableTest {

    @Test
    public void writeMarshallable() {
        final Container c = new Container();
        String s = c.toString();
    }

    private static class Container extends SelfDescribingMarshallable {
        BmExample f = new BmExample();
    }

    public static class BmExample implements BytesMarshallable {
        public void readMarshallable(BytesIn bytes) throws IORuntimeException {
        }
        public void writeMarshallable(BytesOut bytes) {
        }
    }
}
```

**Comment by RobAustin** [comment]
Running the code above produces this error

```

java.lang.NoClassDefFoundError: net/openhft/chronicle/core/util/CoreDynamicEnum

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.openhft.chronicle.wire.WireMarshaller.leafable(WireMarshaller.java:103)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.openhft.chronicle.wire.WireMarshaller.of(WireMarshaller.java:92)
	at net.openhft.chronicle.wire.WireMarshaller.lambda$static$0(WireMarshaller.java:51)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:55)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at net.openhft.chronicle.wire.TextWire$TextValueOut.marshallable(TextWire.java:1874)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:440)
	at net.openhft.chronicle.wire.WireType.asBytes(WireType.java:453)
	at net.openhft.chronicle.wire.WireType.asString(WireType.java:442)
	at net.openhft.chronicle.wire.Marshallable.$toString(Marshallable.java:54)
	at net.openhft.chronicle.wire.AbstractCommonMarshallable.toString(AbstractCommonMarshallable.java:40)
	at net.openhft.chronicle.wire.InnerBytesMarshallableTest.writeMarshallable(InnerBytesMarshallableTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.ClassNotFoundException: net.openhft.chronicle.core.util.CoreDynamicEnum
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 58 more
```

**Comment by RobAustin** [comment]
running this code produces this issue:
```
java.lang.UnsupportedOperationException
	at net.openhft.chronicle.wire.ValueOut.bytesMarshallable(ValueOut.java:695)
	at net.openhft.chronicle.wire.ValueOut.object(ValueOut.java:623)
	at net.openhft.chronicle.wire.ValueOut.untypedObject(ValueOut.java:786)
	at net.openhft.chronicle.wire.ValueOut.object(ValueOut.java:514)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.getValue(WireMarshaller.java:639)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.write(WireMarshaller.java:489)
	at net.openhft.chronicle.wire.WireMarshaller.writeMarshallable(WireMarshaller.java:197)
	at net.openhft.chronicle.wire.Marshallable.writeMarshallable(Marshallable.java:143)
	at net.openhft.chronicle.wire.TextWire$TextValueOut.marshallable(TextWire.java:1896)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:440)
	at net.openhft.chronicle.wire.WireType.asBytes(WireType.java:453)
	at net.openhft.chronicle.wire.WireType.asString(WireType.java:442)
	at net.openhft.chronicle.wire.Marshallable.$toString(Marshallable.java:54)
	at net.openhft.chronicle.wire.AbstractCommonMarshallable.toString(AbstractCommonMarshallable.java:40)
	at net.openhft.chronicle.wire.InnerBytesMarshallableTest.writeMarshallable(InnerBytesMarshallableTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by RobAustin** [comment]
Adding Mashable to the interface fixes it.

![image](https://user-images.githubusercontent.com/6506056/95193240-676ec400-07cb-11eb-8884-29f30b87b51d.png)

**Comment by RobAustin** [comment]
to now output:

```
!net.openhft.chronicle.wire.InnerBytesMarshallableTest$Container {
  f: {
  }
}
```

**Comment by JerryShea** [comment]
But it worked before

**Comment by RobAustin** [comment]
Understood, is this change to the interface acceptable  ?

**Comment by JerryShea** [comment]
Not really. Client code

**Comment by peter-lawrey** [comment]
`ByteMarshallable` is in `bytes` not `wire` and it's `toString()` rightly produces a hex dump.
The fact it happened to do something in nested in a Marshallable before wasn't intended behaviour.

If they want to dump and binary to BinaryWire and text to TextWire they should be using `BytesInBinaryMarshallable`.

If we are to support the behaviour this implies we need to add some tests to show that BytesMarshallable are assumed to be Marshallable in some cases.

**Comment by JerryShea** [comment]
Yes - understand now - thanks chaps
