### ISSUE TITLE
Marshalling DTOs containing floats can fail

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#236]
```
ava.lang.IllegalStateException: value=0.1 can not be represented as a float
	at net.openhft.chronicle.wire.TextWire$TextValueIn.float32(TextWire.java:3419)
	at net.openhft.chronicle.wire.WireMarshaller$FloatFieldAccess.setValue(WireMarshaller.java:1648)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:570)
	at net.openhft.chronicle.wire.WireMarshallerForUnexpectedFields.readMarshallable(WireMarshallerForUnexpectedFields.java:66)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.AbstractEventCfg.readMarshallable(AbstractEventCfg.java:14)
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:50)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.marshallable(TextWire.java:3135)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:461)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:527)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:536)
	at net.openhft.chronicle.wire.WireType.fromString(WireType.java:497)
	at net.openhft.chronicle.wire.JSONWireTest.testFloatFromJson(JSONWireTest.java:191)
```

Should we round (e.g. `if (Maths.round8(((float) d)) != d)`) before comparing here? The float representation of 0.1 is 0.10000000149011612
```
            double d = float64();
            if ((double) (((float) d)) != d)
                throw new IllegalStateException("value=" + d + " can not be represented as a float");
```

**Comment by JerryShea** [comment]
@peter-k-lawrey please review the fix. Better to suffer a loss of precision than an unexpected exception
