### ISSUE TITLE
Cannot write a map implementing class which is parametrized by single type

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#336]
```
public class TestMapMain {
    public static void main(String[] args) {
        Bytes bytes = Bytes.allocateElasticOnHeap();

        final Wire wire = WireType.BINARY.apply(bytes);

        wire.getValueOut().object(new Value(2, "b"));

        final Object object = wire.getValueIn().object();

        System.out.println(object);
    }

    private static class Value extends SelfDescribingMarshallable implements BytesMarshallable {
        private IntMap<String> map = new IntMap<>();

        public Value(int x, String y) {
            map.put(x, y);
        }
    }

    private static class IntMap<T> extends HashMap<Integer, T> {
    }
}
```
will produce exception:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at net.openhft.chronicle.wire.WireMarshaller$MapFieldAccess.<init>(WireMarshaller.java:1258)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.create(WireMarshaller.java:431)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at net.openhft.chronicle.wire.WireMarshaller.of(WireMarshaller.java:87)
	at net.openhft.chronicle.wire.WireMarshaller.lambda$static$0(WireMarshaller.java:51)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:54)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at net.openhft.chronicle.wire.Marshallable.writeMarshallable(Marshallable.java:131)
	at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:1855)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:427)
	at net.openhft.chronicle.wire.ValueOut.object(ValueOut.java:658)
	at feed.replication.TestMapMain.main(TestMapMain.java:21)
```

Wire assumes that map implementing class is always parametrized by `<K, V>`, but it's not uncommon for map implementations to e.g. only parametrize on `<V>`.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea10](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea10), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
