### ISSUE TITLE
WireMarshaller silently ignores a missing alias

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#424]
This is the root cause of https://github.com/ChronicleEnterprise/Chronicle-FIX/issues/966

This exception, that occurs because of a missing alias
```
java.lang.IllegalArgumentException: Cannot find a class for MissingAlias are you missing an alias?
	at net.openhft.chronicle.wire.Wires.tupleFor(Wires.java:619)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.typePrefixOrObject(TextWire.java:3167)
	at net.openhft.chronicle.wire.JSONWire$JSONValueIn.typePrefixOrObject(JSONWire.java:419)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:526)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:529)
	at net.openhft.chronicle.wire.JSONWire$JSONValueIn.object(JSONWire.java:408)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:748)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:632)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:303)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:296)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:355)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:185)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.marshallable(TextWire.java:3266)
	at net.openhft.chronicle.wire.JSONWire$JSONValueIn.marshallable(JSONWire.java:436)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:493)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:574)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:518)
	at net.openhft.chronicle.wire.JSONWire$JSONValueIn.object(JSONWire.java:403)
```
is silently swallowed by https://github.com/OpenHFT/Chronicle-Wire/blob/cc33a71e09c13b5a355900ed340e22d1d21950b4/src/main/java/net/openhft/chronicle/wire/WireMarshaller.java#L748-L756

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea4](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea4), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
