### ISSUE TITLE
Java11 support - IllegalAccessException for the Cleaner

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Wire#49]
Meta-issue for tracking work on Java9 compatibility

**Comment by RobAustin** [comment]
@tomshercliff please test / fix chronicle wire to work with java 9

**Comment by tomshercliff** [comment]
Repurposing this for the work to run on Java11 (compiled on Java8).

Seeing the below issue when running BinaryWireTest:
[main] WARN net.openhft.chronicle.core.cleaner.impl.reflect.ReflectionBasedByteBufferCleanerService - Failed to clean buffer
java.lang.IllegalAccessException: class net.openhft.chronicle.core.cleaner.impl.reflect.ReflectionBasedByteBufferCleanerService cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @735b478
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:352)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at net.openhft.chronicle.core.cleaner.impl.reflect.ReflectionBasedByteBufferCleanerService.clean(ReflectionBasedByteBufferCleanerService.java:30)
	at net.openhft.chronicle.bytes.NativeBytesStore.performRelease(NativeBytesStore.java:542)
	at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:81)
	at net.openhft.chronicle.bytes.NativeBytesStore.release(NativeBytesStore.java:291)
	at net.openhft.chronicle.bytes.AbstractBytes.performRelease(AbstractBytes.java:291)
	at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:81)
	at net.openhft.chronicle.bytes.AbstractBytes.release(AbstractBytes.java:469)
	at net.openhft.chronicle.wire.BinaryWireTest.testUsingEvents(BinaryWireTest.java:828)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input: partial character at end

	at net.openhft.chronicle.bytes.BytesInternal.parseUtf82(BytesInternal.java:571)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:454)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:150)
	at net.openhft.chronicle.bytes.AppendableUtil.parseUtf8(AppendableUtil.java:47)
	at net.openhft.chronicle.bytes.util.UTF8StringInterner.getValue(UTF8StringInterner.java:40)
	at net.openhft.chronicle.bytes.util.UTF8StringInterner.getValue(UTF8StringInterner.java:28)
	at net.openhft.chronicle.bytes.util.AbstractInterner.intern(AbstractInterner.java:77)
	at net.openhft.chronicle.bytes.util.AbstractInterner.intern(AbstractInterner.java:51)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.text(BinaryWire.java:2203)
	at net.openhft.chronicle.wire.ValueIn.text(ValueIn.java:49)
	at net.openhft.chronicle.wire.BinaryWireTest.lambda$testLongString$42(BinaryWireTest.java:751)
	at net.openhft.chronicle.wire.WireInternal.lambda$readData$0(WireInternal.java:153)
	at net.openhft.chronicle.bytes.StreamingDataInput.readWithLength(StreamingDataInput.java:104)
	at net.openhft.chronicle.wire.WireInternal.readData(WireInternal.java:153)
	at net.openhft.chronicle.wire.WireIn.readDocument(WireIn.java:153)
	at net.openhft.chronicle.wire.BinaryWireTest.testLongString(BinaryWireTest.java:751)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.13 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.13), BOM-1.16.125 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.125)

**Comment by epaulson10** [comment]
I am getting this warning today while using Java 11 with the latest version of Chronicle-Queue. I see that the changes that @epickrram made to the pom.xml file to address this were removed in 66996d3bca6b88cf9808e875f294c9651e1a8b8f last year. Was this intentional?

**Comment by dpisklov** [comment]
@epaulson10 in the commit you referenced, java9 profile was removed which (a) doesn't affect Java 11 and (b) doesn't affect consumers anyway.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
