### ISSUE TITLE
Exception when aliasing typed marshallable

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#739]
```
java.lang.UnsupportedOperationException: ALIAS my-alias-name
	at net.openhft.chronicle.wire.YamlWire$TextValueIn.getBracketType(YamlWire.java:970)
	at net.openhft.chronicle.wire.Wires.object1(Wires.java:643)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:602)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:554)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:1075)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:937)
	at net.openhft.chronicle.wire.WireMarshallerForUnexpectedFields.readMarshallable(WireMarshallerForUnexpectedFields.java:78)
	at net.openhft.chronicle.wire.AbstractMarshallableCfg.readMarshallable(AbstractMarshallableCfg.java:52)
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:51)
	at net.openhft.chronicle.wire.YamlWire$TextValueIn.marshallable(YamlWire.java:1648)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:562)
	at net.openhft.chronicle.wire.Wires.object1(Wires.java:658)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:602)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:554)
	at net.openhft.chronicle.wire.YamlWire$TextValueIn.objectWithInferredType0(YamlWire.java:1902)
	at net.openhft.chronicle.wire.YamlWire$TextValueIn.objectWithInferredType(YamlWire.java:1880)
	at net.openhft.chronicle.wire.YamlWire$TextValueIn.typedMarshallable(YamlWire.java:1710)
```
Test pending

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea27](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea27), [BOM-2.24ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea86)
